import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

const services = [
  {
    serviceId: 'destiny_matrix',
    titleRu: 'Матрица судьбы',
    titleEn: 'Destiny Matrix',
    descriptionRu: 'Кармические задачи, таланты, предназначение',
    descriptionEn: 'Karmic tasks, talents, life purpose',
    hookRu: 'Почему вы повторяете одни и те же сценарии?',
    hookEn: 'Why do you repeat the same patterns?',
    priceBasicRUB: 3500,
    priceBasicUSD: 39,
    priceFullRUB: 5500,
    priceFullUSD: 61,
    icon: '🔮',
    color: 'from-purple-600 to-indigo-700',
    featuresBasic: ['Базовый расчёт матрицы', 'Основные арканы', 'Кармические задачи', 'Таланты и способности'],
    featuresFull: ['Всё из базового', 'Полная расшифровка всех позиций', 'Детальный анализ отношений', 'Рекомендации по развитию', 'Кармические долги'],
    buttonTextRu: 'Рассчитать матрицу',
    buttonTextEn: 'Calculate Matrix',
    isActive: true,
    sortOrder: 1,
  },
  {
    serviceId: 'child_numerology',
    titleRu: 'Детская нумерология',
    titleEn: 'Child Numerology',
    descriptionRu: 'Таланты, страхи, рекомендации родителям',
    descriptionEn: 'Talents, fears, recommendations for parents',
    hookRu: 'Что ваш ребёнок прячет от вас?',
    hookEn: 'What is your child hiding from you?',
    priceBasicRUB: 2900,
    priceBasicUSD: 32,
    priceFullRUB: 4900,
    priceFullUSD: 54,
    icon: '👶',
    color: 'from-pink-500 to-rose-600',
    featuresBasic: ['Характер ребёнка', 'Скрытые таланты', 'Основные страхи', 'Рекомендации родителям'],
    featuresFull: ['Всё из базового', 'Отношения с родителями', 'Выбор профессии', 'Здоровье и энергия', 'План развития по возрастам'],
    buttonTextRu: 'Узнать ребёнка',
    buttonTextEn: 'Discover Your Child',
    isActive: true,
    sortOrder: 2,
  },
  {
    serviceId: 'compatibility',
    titleRu: 'Совместимость',
    titleEn: 'Compatibility',
    descriptionRu: 'Отношения, брак, конфликты, кармические связи',
    descriptionEn: 'Relationships, marriage, conflicts, karmic connections',
    hookRu: 'Почему вы ссоритесь?',
    hookEn: 'Why do you argue?',
    priceBasicRUB: 3900,
    priceBasicUSD: 43,
    priceFullRUB: 5900,
    priceFullUSD: 66,
    icon: '💞',
    color: 'from-red-500 to-pink-600',
    featuresBasic: ['Совместимость по датам', 'Сильные стороны пары', 'Зоны конфликтов', 'Базовые рекомендации'],
    featuresFull: ['Всё из базового', 'Кармические связи', 'Сексуальная совместимость', 'Финансовая совместимость', 'Прогноз отношений', 'Детальные рекомендации'],
    buttonTextRu: 'Проверить совместимость',
    buttonTextEn: 'Check Compatibility',
    isActive: true,
    sortOrder: 3,
  },
  {
    serviceId: 'money_numerology',
    titleRu: 'Денежная нумерология',
    titleEn: 'Money Numerology',
    descriptionRu: 'Денежный код, блоки, кармические долги',
    descriptionEn: 'Money code, blocks, karmic debts',
    hookRu: 'Почему деньги приходят, но не задерживаются?',
    hookEn: 'Why does money come but not stay?',
    priceBasicRUB: 3900,
    priceBasicUSD: 43,
    priceFullRUB: 5900,
    priceFullUSD: 66,
    icon: '💰',
    color: 'from-yellow-500 to-amber-600',
    featuresBasic: ['Расчёт денежного кода', 'Основные блоки', 'Кармические долги', 'Базовые рекомендации'],
    featuresFull: ['Всё из базового', 'Детальный анализ блоков', 'Благоприятные периоды', 'Способы активации', 'Инвестиционный потенциал', 'Персональные практики'],
    buttonTextRu: 'Активировать деньги',
    buttonTextEn: 'Activate Money',
    isActive: true,
    sortOrder: 4,
  },
  {
    serviceId: 'yearly_forecast',
    titleRu: 'Годовой прогноз',
    titleEn: 'Yearly Forecast',
    descriptionRu: 'Что ждёт в ближайшие 12 месяцев',
    descriptionEn: 'What awaits in the next 12 months',
    hookRu: 'Что принесёт вам этот год?',
    hookEn: 'What will this year bring you?',
    priceBasicRUB: 4900,
    priceBasicUSD: 54,
    priceFullRUB: 6900,
    priceFullUSD: 77,
    icon: '📅',
    color: 'from-blue-500 to-cyan-600',
    featuresBasic: ['Прогноз на 12 месяцев', 'Ключевые события', 'Благоприятные периоды', 'Предупреждения'],
    featuresFull: ['Всё из базового', 'Детальный прогноз по месяцам', 'Финансовый прогноз', 'Прогноз отношений', 'Здоровье и энергия', 'Рекомендации по месяцам'],
    buttonTextRu: 'Узнать будущее',
    buttonTextEn: 'Discover Future',
    isActive: true,
    sortOrder: 5,
  },
  {
    serviceId: 'pythagorean_full',
    titleRu: 'Квадрат Пифагора',
    titleEn: 'Pythagorean Square',
    descriptionRu: 'Характер, линии силы, пустые ячейки',
    descriptionEn: 'Character, power lines, empty cells',
    hookRu: 'Как цифры управляют вашим характером',
    hookEn: 'How numbers control your character',
    priceBasicRUB: 2900,
    priceBasicUSD: 32,
    priceFullRUB: 4900,
    priceFullUSD: 54,
    icon: '🧮',
    color: 'from-green-500 to-emerald-600',
    featuresBasic: ['Построение квадрата', 'Разбор всех ячеек', 'Основные линии', 'Характер и темперамент'],
    featuresFull: ['Всё из базового', 'Все 8 линий квадрата', 'Пустые ячейки', 'Переизбыток цифр', 'Совместимость с другими', 'Рекомендации по развитию'],
    buttonTextRu: 'Построить квадрат',
    buttonTextEn: 'Build Square',
    isActive: true,
    sortOrder: 6,
  },
  {
    serviceId: 'pro_access',
    titleRu: 'Профи-доступ',
    titleEn: 'Pro Access',
    descriptionRu: 'Готовые расчёты для работы с клиентами',
    descriptionEn: 'Ready calculations for client work',
    hookRu: 'Хватит считать вручную',
    hookEn: 'Stop calculating manually',
    priceBasicRUB: 500,
    priceBasicUSD: 6,
    priceFullRUB: 2500,
    priceFullUSD: 28,
    icon: '🧠',
    color: 'from-slate-600 to-gray-700',
    featuresBasic: ['Разовый отчёт', 'Все расчёты', 'Профессиональный формат', 'Без воды'],
    featuresFull: ['До 30 отчётов/месяц', 'Все типы расчётов', 'White Label (опционально)', 'Приоритетная поддержка', 'API доступ'],
    buttonTextRu: 'Начать работать',
    buttonTextEn: 'Start Working',
    isActive: true,
    sortOrder: 7,
  },
  {
    serviceId: 'gift_certificate',
    titleRu: 'Подарочный сертификат',
    titleEn: 'Gift Certificate',
    descriptionRu: 'Подарите близким персональный нумерологический отчёт',
    descriptionEn: 'Gift your loved ones a personal numerology report',
    hookRu: 'Лучший подарок — знание о себе',
    hookEn: 'The best gift is self-knowledge',
    priceBasicRUB: 2900,
    priceBasicUSD: 32,
    priceFullRUB: 5900,
    priceFullUSD: 66,
    icon: '🎁',
    color: 'from-fuchsia-500 to-purple-600',
    featuresBasic: ['Красивая электронная открытка', 'Уникальный код активации', 'Базовый отчёт на выбор', 'Персональное поздравление'],
    featuresFull: ['Всё из базового', 'Полный отчёт любого типа', 'Премиум дизайн открытки', 'Видео-поздравление', 'Срок действия 1 год'],
    buttonTextRu: 'Подарить',
    buttonTextEn: 'Gift Now',
    isActive: true,
    sortOrder: 8,
  },
  {
    serviceId: 'consultation',
    titleRu: 'Консультация нумеролога',
    titleEn: 'Numerologist Consultation',
    descriptionRu: 'Персональная консультация с профессиональным нумерологом',
    descriptionEn: 'Personal consultation with professional numerologist',
    hookRu: 'Получите ответы на свои вопросы',
    hookEn: 'Get answers to your questions',
    priceBasicRUB: 7000,
    priceBasicUSD: 78,
    priceFullRUB: 12000,
    priceFullUSD: 133,
    icon: '👤',
    color: 'from-violet-600 to-purple-700',
    featuresBasic: ['Онлайн-консультация 60 минут', 'Разбор вашей матрицы судьбы', 'Ответы на 3 вопроса', 'Запись консультации', 'Краткие рекомендации'],
    featuresFull: ['Всё из базового', 'Консультация 90 минут', 'Неограниченное количество вопросов', 'Детальный письменный отчёт', 'Персональные практики', 'Поддержка 30 дней после консультации'],
    buttonTextRu: 'Записаться',
    buttonTextEn: 'Book Now',
    isActive: true,
    sortOrder: 9,
  },
];

async function main() {
  console.log('Начинаем заполнение базы данных услугами...');

  for (const service of services) {
    const result = await prisma.premiumService.upsert({
      where: { serviceId: service.serviceId },
      update: service,
      create: service,
    });
    console.log(`✓ Создана/обновлена услуга: ${result.titleRu}`);
  }

  console.log('\n✅ Все услуги успешно добавлены в базу данных!');
}

main()
  .catch((e) => {
    console.error('❌ Ошибка при заполнении базы данных:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
